### ISSUE TITLE
Allow instantiation of ServiceRequestFactory when no credentials/UUID are provided

### ISSUE THREAD

**Issue by ryanisnan** [sokanu/spylib#13]
We should support cases where no authentication has been provided. In these cases, 401s will occur most likely. In some cases, services may allow unauthenticated requests, which we should support.

Additionally, when a 401 is returned, our call to `fetch_new_tokens` should simply not do anything because there are no credentials to use to re-authenticate, nor is there a refresh token to do a token swap.

**Comment by alekhrycaiko** [comment]
Makes sense, this should be a case we handle.
